using UnityEngine;

namespace App.VFX
{
    /// <summary>
    /// This class was generated by AI.
    /// </summary>
    public static class ParticleSystemCopier
    {
        public static void CopyParticleSystem(ParticleSystem src, ParticleSystem dst)
        {
            if (src == null || dst == null) return;

            dst.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);

            CopyMain(src.main, dst.main);
            CopyEmission(src.emission, dst.emission);
            CopyShape(src.shape, dst.shape);
            CopyVelocityOverLifetime(src.velocityOverLifetime, dst.velocityOverLifetime);
            CopyLimitVelocityOverLifetime(src.limitVelocityOverLifetime, dst.limitVelocityOverLifetime);
            CopyInheritVelocity(src.inheritVelocity, dst.inheritVelocity);
            CopyForceOverLifetime(src.forceOverLifetime, dst.forceOverLifetime);
            CopyColorOverLifetime(src.colorOverLifetime, dst.colorOverLifetime);
            CopyColorBySpeed(src.colorBySpeed, dst.colorBySpeed);
            CopySizeOverLifetime(src.sizeOverLifetime, dst.sizeOverLifetime);
            CopySizeBySpeed(src.sizeBySpeed, dst.sizeBySpeed);
            CopyRotationOverLifetime(src.rotationOverLifetime, dst.rotationOverLifetime);
            CopyRotationBySpeed(src.rotationBySpeed, dst.rotationBySpeed);
            CopyExternalForces(src.externalForces, dst.externalForces);
            CopyNoise(src.noise, dst.noise);
            CopyCollision(src.collision, dst.collision);
            CopyTrigger(src.trigger, dst.trigger);
            CopySubEmitters(src.subEmitters, dst.subEmitters);
            CopyTextureSheetAnimation(src.textureSheetAnimation, dst.textureSheetAnimation);
            CopyLights(src.lights, dst.lights);
            CopyTrails(src.trails, dst.trails);
            //CopyCustomData(src.customData, dst.customData);

            CopyRenderer(src, dst);

            dst.Play(true);
        }

        #region Modules

        static void CopyMain(ParticleSystem.MainModule s, ParticleSystem.MainModule d)
        {
            d.duration = s.duration;
            d.loop = s.loop;
            d.prewarm = s.prewarm;
            d.startDelay = s.startDelay;
            d.startLifetime = s.startLifetime;
            d.startSpeed = s.startSpeed;
            d.startSize = s.startSize;
            d.startRotation = s.startRotation;
            d.startColor = s.startColor;
            d.gravityModifier = s.gravityModifier;
            d.simulationSpace = s.simulationSpace;
            d.simulationSpeed = s.simulationSpeed;
            d.scalingMode = s.scalingMode;
            d.playOnAwake = s.playOnAwake;
            d.maxParticles = s.maxParticles;
            d.emitterVelocityMode = s.emitterVelocityMode;
            d.stopAction = s.stopAction;
            d.cullingMode = s.cullingMode;
            d.ringBufferMode = s.ringBufferMode;
            d.ringBufferLoopRange = s.ringBufferLoopRange;
        }

        static void CopyEmission(ParticleSystem.EmissionModule s, ParticleSystem.EmissionModule d)
        {
            d.enabled = s.enabled;
            d.rateOverTime = s.rateOverTime;
            d.rateOverDistance = s.rateOverDistance;

            var bursts = new ParticleSystem.Burst[s.burstCount];
            s.GetBursts(bursts);
            d.SetBursts(bursts);
        }

        static void CopyShape(ParticleSystem.ShapeModule s, ParticleSystem.ShapeModule d)
        {
            d.enabled = s.enabled;
            d.shapeType = s.shapeType;
            d.radius = s.radius;
            d.radiusThickness = s.radiusThickness;
            d.angle = s.angle;
            d.length = s.length;
            d.arc = s.arc;
            d.arcMode = s.arcMode;
            d.arcSpread = s.arcSpread;
            d.position = s.position;
            d.rotation = s.rotation;
            d.scale = s.scale;
            d.alignToDirection = s.alignToDirection;
            d.randomDirectionAmount = s.randomDirectionAmount;
            d.sphericalDirectionAmount = s.sphericalDirectionAmount;
        }

        static void CopyVelocityOverLifetime(ParticleSystem.VelocityOverLifetimeModule s, ParticleSystem.VelocityOverLifetimeModule d)
        {
            d.enabled = s.enabled;
            d.space = s.space;
            d.x = s.x;
            d.y = s.y;
            d.z = s.z;
            d.orbitalX = s.orbitalX;
            d.orbitalY = s.orbitalY;
            d.orbitalZ = s.orbitalZ;
            d.radial = s.radial;
            d.speedModifier = s.speedModifier;
        }

        static void CopyLimitVelocityOverLifetime(ParticleSystem.LimitVelocityOverLifetimeModule s, ParticleSystem.LimitVelocityOverLifetimeModule d)
        {
            d.enabled = s.enabled;
            d.space = s.space;
            d.limitX = s.limitX;
            d.limitY = s.limitY;
            d.limitZ = s.limitZ;
            d.limit = s.limit;
            d.dampen = s.dampen;
            d.separateAxes = s.separateAxes;
        }

        static void CopyInheritVelocity(ParticleSystem.InheritVelocityModule s, ParticleSystem.InheritVelocityModule d)
        {
            d.enabled = s.enabled;
            d.mode = s.mode;
            d.curve = s.curve;
        }

        static void CopyForceOverLifetime(ParticleSystem.ForceOverLifetimeModule s, ParticleSystem.ForceOverLifetimeModule d)
        {
            d.enabled = s.enabled;
            d.space = s.space;
            d.x = s.x;
            d.y = s.y;
            d.z = s.z;
        }

        static void CopyColorOverLifetime(ParticleSystem.ColorOverLifetimeModule s, ParticleSystem.ColorOverLifetimeModule d)
        {
            d.enabled = s.enabled;
            d.color = s.color;
        }

        static void CopyColorBySpeed(ParticleSystem.ColorBySpeedModule s, ParticleSystem.ColorBySpeedModule d)
        {
            d.enabled = s.enabled;
            d.color = s.color;
            d.range = s.range;
        }

        static void CopySizeOverLifetime(ParticleSystem.SizeOverLifetimeModule s, ParticleSystem.SizeOverLifetimeModule d)
        {
            d.enabled = s.enabled;
            d.size = s.size;
            d.separateAxes = s.separateAxes;
            d.x = s.x;
            d.y = s.y;
            d.z = s.z;
        }

        static void CopySizeBySpeed(ParticleSystem.SizeBySpeedModule s, ParticleSystem.SizeBySpeedModule d)
        {
            d.enabled = s.enabled;
            d.size = s.size;
            d.range = s.range;
            d.separateAxes = s.separateAxes;
        }

        static void CopyRotationOverLifetime(ParticleSystem.RotationOverLifetimeModule s, ParticleSystem.RotationOverLifetimeModule d)
        {
            d.enabled = s.enabled;
            d.separateAxes = s.separateAxes;
            d.x = s.x;
            d.y = s.y;
            d.z = s.z;
        }

        static void CopyRotationBySpeed(ParticleSystem.RotationBySpeedModule s, ParticleSystem.RotationBySpeedModule d)
        {
            d.enabled = s.enabled;
            d.separateAxes = s.separateAxes;
            d.x = s.x;
            d.y = s.y;
            d.z = s.z;
            d.range = s.range;
        }

        static void CopyExternalForces(ParticleSystem.ExternalForcesModule s, ParticleSystem.ExternalForcesModule d)
        {
            d.enabled = s.enabled;
            d.multiplier = s.multiplier;
            d.influenceFilter = s.influenceFilter;
        }

        static void CopyNoise(ParticleSystem.NoiseModule s, ParticleSystem.NoiseModule d)
        {
            d.enabled = s.enabled;
            d.strength = s.strength;
            d.frequency = s.frequency;
            d.scrollSpeed = s.scrollSpeed;
            d.damping = s.damping;
            d.octaveCount = s.octaveCount;
            d.octaveMultiplier = s.octaveMultiplier;
            d.octaveScale = s.octaveScale;
            d.quality = s.quality;
        }

        static void CopyCollision(ParticleSystem.CollisionModule s, ParticleSystem.CollisionModule d)
        {
            d.enabled = s.enabled;
            d.type = s.type;
            d.mode = s.mode;
            d.dampen = s.dampen;
            d.bounce = s.bounce;
            d.lifetimeLoss = s.lifetimeLoss;
            d.collidesWith = s.collidesWith;
            d.enableDynamicColliders = s.enableDynamicColliders;
            d.sendCollisionMessages = s.sendCollisionMessages;
        }

        static void CopyTrigger(ParticleSystem.TriggerModule s, ParticleSystem.TriggerModule d)
        {
            d.enabled = s.enabled;
            d.inside = s.inside;
            d.outside = s.outside;
            d.enter = s.enter;
            d.exit = s.exit;
            d.radiusScale = s.radiusScale;
        }

        static void CopySubEmitters(ParticleSystem.SubEmittersModule s, ParticleSystem.SubEmittersModule d)
        {
            d.enabled = s.enabled;
            for (int i = 0; i < s.subEmittersCount; i++)
            {
                d.AddSubEmitter(
                    s.GetSubEmitterSystem(i),
                    s.GetSubEmitterType(i),
                    s.GetSubEmitterProperties(i));
            }
        }

        static void CopyTextureSheetAnimation(ParticleSystem.TextureSheetAnimationModule s, ParticleSystem.TextureSheetAnimationModule d)
        {
            d.enabled = s.enabled;
            d.mode = s.mode;
            d.numTilesX = s.numTilesX;
            d.numTilesY = s.numTilesY;
            d.animation = s.animation;
            d.frameOverTime = s.frameOverTime;
            d.startFrame = s.startFrame;
            d.cycleCount = s.cycleCount;
            d.rowMode = s.rowMode;
        }

        static void CopyLights(ParticleSystem.LightsModule s, ParticleSystem.LightsModule d)
        {
            d.enabled = s.enabled;
            d.light = s.light;
            d.ratio = s.ratio;
            d.range = s.range;
            d.intensity = s.intensity;
        }

        static void CopyTrails(ParticleSystem.TrailModule s, ParticleSystem.TrailModule d)
        {
            d.enabled = s.enabled;
            d.mode = s.mode;
            d.ratio = s.ratio;
            d.lifetime = s.lifetime;
            d.widthOverTrail = s.widthOverTrail;
            d.colorOverLifetime = s.colorOverLifetime;
            d.dieWithParticles = s.dieWithParticles;
        }

        // static void CopyCustomData(ParticleSystem.CustomDataModule s, ParticleSystem.CustomDataModule d)
        // {
        //     d.enabled = s.enabled;
        //     for (int i = 0; i < 4; i++)
        //     {
        //         d.SetMode((ParticleSystemCustomData)i, s.GetMode((ParticleSystemCustomData)i));
        //         for (int j = 0; j < 4; j++)
        //         {
        //             d.SetVector(
        //                 (ParticleSystemCustomData)i,
        //                 j,
        //                 s.GetVector((ParticleSystemCustomData)i, j));
        //         }
        //     }
        // }

        static void CopyRenderer(ParticleSystem src, ParticleSystem dst)
        {
            var sr = src.GetComponent<ParticleSystemRenderer>();
            var dr = dst.GetComponent<ParticleSystemRenderer>();
            if (sr == null || dr == null) return;

            dr.renderMode = sr.renderMode;
            dr.sharedMaterial = sr.sharedMaterial;
            dr.trailMaterial = sr.trailMaterial;
            dr.sortingLayerID = sr.sortingLayerID;
            dr.sortingOrder = sr.sortingOrder;
            dr.alignment = sr.alignment;
            dr.shadowCastingMode = sr.shadowCastingMode;
            dr.receiveShadows = sr.receiveShadows;
            dr.enableGPUInstancing = sr.enableGPUInstancing;
        }

        #endregion
    }
}